version: 2
updates:
  - package-ecosystem: npm
    directory: /
    reviewers:
      - TSRBerry
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - TSRBerry
    schedule:
      interval: daily
