name: Fix dependabot PRs

on:
  pull_request:
    branches:
      - "dependabot/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  pnpm-lock:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Configure git
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install dependencies (no-frozen-lockfile)
        run: pnpm install --no-frozen-lockfile

      - name: Check if files have been modified
        id: mod_check
        run: |
          [[ $(git status -s | wc -l) -le 1 ]] \
          && echo "is-dirty=false" >> "$GITHUB_OUTPUT" \
          || echo "is-dirty=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.mod_check.outputs.is-dirty == 'true'
        run: |
          git add .
          git commit -m "Update pnpm-lock.yaml"
          git push
